### ISSUE TITLE
relative path error

### ISSUE THREAD

**Issue by noraj** [bannsec/stegoVeritas#13]
relative path doesn't work:

```
$ ~/CTF/tools/stegoVeritas/stegoveritas.py steg1/secret.jpg 
Type:   JPEG (ISO 10918)
Mode:   RGB

Checking Meta Data

Exif Data
=========
Image XResolution:      1
Image YResolution:      1
Image ResolutionUnit:   Not Absolute
Image Artist:   d0ntTr!
Image YCbCrPositioning: Centered


Checking for trailing data
Trailing Data Discovered... Saving
b'd0ntTr!'
Running image filters
Traceback (most recent call last):
  File "/home/noraj/CTF/tools/stegoVeritas/stegoveritas.py", line 70, in <module>
    modules.image.run(fArray,args)
  File "/home/noraj/CTF/tools/stegoVeritas/modules/image/__init__.py", line 98, in run
    autoAnalysis(f,args)
  File "/home/noraj/CTF/tools/stegoVeritas/modules/image/__init__.py", line 29, in autoAnalysis
    modules.image.imageFilters.auto(f,args.outDir)
  File "/home/noraj/CTF/tools/stegoVeritas/modules/image/imageFilters.py", line 87, in auto
    g.save(os.path.join(outDir,fileName + "_" + filt.name.replace(" ","_") + ".png"))
  File "/usr/lib/python3.7/site-packages/PIL/Image.py", line 2004, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/home/noraj/CTF/XXX/files/results/steg1/secret.jpg_Edge-enhance.png'
```

file in current folder works:

```
$ ~/CTF/tools/stegoVeritas/stegoveritas.py secret.jpg      
Type:   JPEG (ISO 10918)
Mode:   RGB

Checking Meta Data

Exif Data
=========
Image XResolution:      1
Image YResolution:      1
Image ResolutionUnit:   Not Absolute
Image Artist:   d0ntTr!
Image YCbCrPositioning: Centered


Checking for trailing data
Trailing Data Discovered... Saving
b'd0ntTr!'
Running image filters
Attempting to brute force LSB items
Trying 0.0.0
Trying 1.1.1
Trying 2.2.2
```

absolute path works:

```
$ ~/CTF/tools/stegoVeritas/stegoveritas.py /home/noraj/CTF/XXX/files/steg1/secret.jpg
Type:   JPEG (ISO 10918)
Mode:   RGB

Checking Meta Data

Exif Data
=========
Image XResolution:      1
Image YResolution:      1
Image ResolutionUnit:   Not Absolute
Image Artist:   d0ntTr!
Image YCbCrPositioning: Centered


Checking for trailing data
Trailing Data Discovered... Saving
b'd0ntTr!'
Running image filters
Attempting to brute force LSB items
Trying 0.0.0
Trying 1.1.1
```

**Comment by bannsec** [comment]
Looking like you're using an old version. Please verify the error with the current version:

```bash
$ pip3 install stegoveritas
$ stegoveritas_install_deps
```

Then call it as the installed python module. For instance:

```bash
stegoVeritas -h # Note no path to the .py file, can be run from any directory too.
```

**Comment by noraj** [comment]
My bad I didn't do a `git pull`

**Comment by bannsec** [comment]
No worries
