### ISSUE TITLE
get this error when I run stegoveritas /home/user/Desktop/DSWii6x.png

### ISSUE THREAD

**Issue by dieao** [bannsec/stegoVeritas#29]
ERROR:stegoveritas.helpers:unrecognized data stream contents when reading image file
^[[AERROR:stegoveritas.helpers:list index out of range
ERROR:stegoveritas.helpers:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/modules/image/analysis/brute_lsb.py", line 13, in run_dump
    image.veritas.test_output(o)
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/stegoveritas.py", line 119, in test_output
    table.add_row([hex(result.offset), 'Extracted', result.description, os.path.basename(module.extractor.output[result.file.path].extracted[result.offset].files[0])])
IndexError: list index out of range
"""
ERROR:stegoveritas.helpers:list index out of range
ERROR:stegoveritas.helpers:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/modules/image/analysis/brute_lsb.py", line 13, in run_dump
    image.veritas.test_output(o)
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/stegoveritas.py", line 119, in test_output
    table.add_row([hex(result.offset), 'Extracted', result.description, os.path.basename(module.extractor.output[result.file.path].extracted[result.offset].files[0])])
IndexError: list index out of range
"""
ERROR:stegoveritas.helpers:[Errno 2] No such file or directory
ERROR:stegoveritas.helpers:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/modules/image/analysis/brute_lsb.py", line 13, in run_dump
    image.veritas.test_output(o)
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/stegoveritas.py", line 99, in test_output
    saved_dir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
"""
ERROR:stegoveritas.helpers:[Errno 2] No such file or directory
ERROR:stegoveritas.helpers:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/modules/image/analysis/brute_lsb.py", line 13, in run_dump
    image.veritas.test_output(o)
  File "/usr/local/lib/python3.8/dist-packages/stegoveritas/stegoveritas.py", line 99, in test_output
    saved_dir = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

**Comment by bannsec** [comment]
Do you have the example file?

**Comment by dieao** [comment]
![DSWii6x](https://user-images.githubusercontent.com/62806098/86362591-6d558600-bc6d-11ea-81c5-342da53d9f66.png)

**Comment by dieao** [comment]
I a doing something called defend the web and this is one of the images to decrypt

**Comment by bannsec** [comment]
it appears that the image you posted is corrupted. might be worth looking at it in 010editor or something.
