### ISSUE TITLE
imageLSB.py error

### ISSUE THREAD

**Issue by noraj** [bannsec/stegoVeritas#3]
Since I don't know when a error occured preventing stegoveritas from doing LSB checks:

```
Traceback (most recent call last):
  File "/home/noraj/CTF/tools/stegoVeritas/stegoveritas.py", line 70, in <module>
    modules.image.run(fArray,args)
  File "/home/noraj/CTF/tools/stegoVeritas/modules/image/__init__.py", line 98, in run
    autoAnalysis(f,args)
  File "/home/noraj/CTF/tools/stegoVeritas/modules/image/__init__.py", line 37, in autoAnalysis
    modules.image.imageLSB.auto(f,args)
  File "/home/noraj/CTF/tools/stegoVeritas/modules/image/imageLSB.py", line 143, in auto
    testOutput(o,args)
  File "/home/noraj/CTF/tools/stegoVeritas/modules/image/imageLSB.py", line 23, in testOutput
    m = magic.from_buffer(b,mime=True)
AttributeError: module 'magic' has no attribute 'from_buffer'
```

I checked I still have teh dependencies. I don't think it's something that change in the script but something on the system.

PS : I'm up to date with the git.

---

I think I found there is 3 libs named exactly python-magic, see [this](https://stackoverflow.com/questions/25286176/how-to-use-python-magic-5-19-1)

```
python-magic 5.29-2
python2-magic 5.29-2
```

**Comment by noraj1337** [comment]
Can you tell in your README or dependency file to install `python-magic` with `pip3 install python-magic` (the one from pypi) and not from distro package manager that may use the other one.

**Comment by noraj1337** [comment]
can close when PR https://github.com/bannsec/stegoVeritas/pull/4 will be merged
