### ISSUE TITLE
stegoveritas_install_deps error on mac

### ISSUE THREAD

**Issue by Maokus** [bannsec/stegoVeritas#33]
stegovaritas was downloaded using ```pip3 install stegoveritas```
```
user@Com - 901 Downloads %  stegoveritas_install_deps 
Traceback (most recent call last):
  File "/Users/user/anaconda3/bin/stegoveritas_install_deps", line 5, in <module>
    from stegoveritas.install_deps import main
  File "/Users/user/anaconda3/lib/python3.8/site-packages/stegoveritas/__init__.py", line 2, in <module>
    from .stegoveritas import StegoVeritas
  File "/Users/user/anaconda3/lib/python3.8/site-packages/stegoveritas/stegoveritas.py", line 15, in <module>
    import magic
  File "/Users/user/anaconda3/lib/python3.8/site-packages/magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

**Comment by bannsec** [comment]
Unfortunately i don't have a mac to test against. python magic notes the following for mac

```

    When using Homebrew: brew install libmagic
    When using macports: port install file
```
