### ISSUE TITLE
Python 3.9 compatibility error

### ISSUE THREAD

**Issue by noraj** [bannsec/stegoVeritas#36]
```
ERROR:stegoveritas.helpers:module 'magic' has no attribute 'from_buffer'
ERROR:stegoveritas.helpers:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/stegoveritas/modules/image/analysis/brute_lsb.py", line 13, in run_dump
    image.veritas.test_output(o)
  File "/usr/lib/python3.9/site-packages/stegoveritas/stegoveritas.py", line 79, in test_output
    m = magic.from_buffer(thing, mime=True)
AttributeError: module 'magic' has no attribute 'from_buffer'
"""
```

**Comment by bannsec** [comment]
Bugfixed a bit. python 3.9 is working fine for me. That specific error, however, is due to installing an incorrect python magic library. I'd recommend double-checking with pip freeze and dpkg -l. The correct library (python-magic) should look something like this:

```python
import magic
magic.version() # 539
```
