### ISSUE TITLE
_dumpLSBRGBA

### ISSUE THREAD

**Issue by adamlinux0** [bannsec/stegoVeritas#6]
```Type:	Portable network graphics
Mode:	RGB

Trying 0.0.0
Traceback (most recent call last):
  File "stegoveritas.py", line 71, in <module>
    modules.image.run(fArray,args)
  File "~/Documents/stegoVeritas-master/modules/image/__init__.py", line 106, in run
    modules.image.imageLSB.auto(f,args)
  File "~/Documents/stegoVeritas-master/modules/image/imageLSB.py", line 142, in auto
    o = _dumpLSBRGBA(f=f,rIndex=[i],gIndex=[i],bIndex=[i])
  File "~/Documents/stegoVeritas-master/modules/image/imageLSB.py", line 93, in _dumpLSBRGBA
    binStr += str(fBytes[byte + 0] >> index & 1)
TypeError: unsupported operand type(s) for >>: 'str' and 'int'

**Comment by adamlinux0** [comment]
also had to fetch a new copy of png.py to suppress errors there, and changed code for

```
# Make the folder if need be
if not os.path.exists('/root/Desktop/stegoVeritas-master/results'):
    os.makedirs(path)
```
otherwise I got an error message

**Comment by adamlinux0** [comment]
nevermind, your shebang should be #!/usr/bin/env python3 instead of #!/usr/bin/env python
