### ISSUE TITLE
ModuleNotFoundError: No module named 'magic'

### ISSUE THREAD

**Issue by kobie2008** [bannsec/stegoVeritas#8]
After correcting 2 instances of /usr/bin/env python to /usr/bin/env python3 i still get this error below. 
OS: Kali 2018.3 rolling

# ./stegoveritas.py art.png 
Type:	Portable network graphics
Mode:	RGBA

Traceback (most recent call last):
  File "./stegoveritas.py", line 69, in <module>
    import modules.image
  File "/opt/stegoVeritas/modules/image/__init__.py", line 1, in <module>
    import modules.image.imageLSB
  File "/opt/stegoVeritas/modules/image/imageLSB.py", line 6, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

**Comment by bannsec** [comment]
Yeah, i haven't refactored this into a actual python library yet. Under dependencies I'm guessing you're missing:

```bash
pip3 install pfp python-magic
```
